version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    container_name: web-application-2-container
    ports:
      - '5683:5432'
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: drizzle
      POSTGRES_DB: db
