version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    container_name: db-container
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: drizzle
      POSTGRES_DB: db
